In [3]:
import pandas as pd

In [19]:
list = [[1,2],[3,4]]
rowNames = ["r1","r2"]
colNames = ["col1","col2"]
df = pd.DataFrame(list,index=rowNames,columns=colNames)
df

    col1  col2
r1     1     2
r2     3     4

In [5]:
df["col1"]

r1    1
r2    3
Name: col1, dtype: int64

In [8]:
df.at["r1","col1"]

1

In [9]:
df.iat[1,1]

4

In [22]:
df2=df.copy(deep=True)

df2["col3"]=[10,11]
df2.loc["r3"]=[100,110,120]
df2

    col1  col2  col3
r1     1     2    10
r2     3     4    11
r3   100   110   120

In [26]:
df2.iloc[0:2,0:2]=[[10,20],[30,40]]
df2.iloc[0:2,0:2]

    col1  col2
r1    10    20
r2    30    40

In [27]:
df2

    col1  col2  col3
r1    10    20    10
r2    30    40    11
r3   100   110   120

In [29]:
df2.iat[0,0]

10

In [30]:
df2.at["r1","col1"]

10

In [32]:
df2.iloc[0]

col1    10
col2    20
col3    10
Name: r1, dtype: int64

In [33]:
df2.loc["r1"]

col1    10
col2    20
col3    10
Name: r1, dtype: int64

In [35]:
df2["col1"]

r1     10
r2     30
r3    100
Name: col1, dtype: int64

In [36]:
df2.iloc[:,0]

r1     10
r2     30
r3    100
Name: col1, dtype: int64

In [38]:
df2.index

Index(['r1', 'r2', 'r3'], dtype='object')

In [39]:
df2.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [40]:
df2[df2.columns[0]]

r1     10
r2     30
r3    100
Name: col1, dtype: int64

In [41]:
df2.loc[:,"col1"]

r1     10
r2     30
r3    100
Name: col1, dtype: int64

In [45]:
df2.loc[df2.index[0] , : ] #singe row

col1    10
col2    20
col3    10
Name: r1, dtype: int64

In [46]:
df2.loc[:,df2.columns[0]] #refer to single columns

r1     10
r2     30
r3    100
Name: col1, dtype: int64

In [47]:
df2

    col1  col2  col3
r1    10    20    10
r2    30    40    11
r3   100   110   120

In [48]:
df2['col1']

r1     10
r2     30
r3    100
Name: col1, dtype: int64

In [50]:
df2[['col1','col3']]

    col1  col3
r1    10    10
r2    30    11
r3   100   120

In [54]:
df2.loc[  :  ,df2.columns[0] ]

r1     10
r2     30
r3    100
Name: col1, dtype: int64

In [55]:
df2.loc[ df2.index[0] , : ]

col1    10
col2    20
col3    10
Name: r1, dtype: int64

In [56]:
df2

    col1  col2  col3
r1    10    20    10
r2    30    40    11
r3   100   110   120

In [57]:
df2[df2["col1"] > 10]

    col1  col2  col3
r2    30    40    11
r3   100   110   120

In [61]:
df2[df2.index == "r1"]

    col1  col2  col3
r1    10    20    10

In [62]:
df2[df2.index.isin ( ["r1","r3"] )]

    col1  col2  col3
r1    10    20    10
r3   100   110   120

In [68]:
df2.index.map({"r1":1 , "r2" : 2, "r3" : 3})

Index([1, 2, 3], dtype='int64')

In [79]:
df2.values.tolist()

[[10, 20, 10], [30, 40, 11], [100, 110, 120]]

In [75]:
df3 = pd.DataFrame([[1,2],[3,4,5],[6,7]])
df3

   0  1    2
0  1  2  NaN
1  3  4  5.0
2  6  7  NaN

In [77]:
df2.shape

(3, 3)

In [111]:
type(df2.shape)

tuple

In [99]:
df3.columns=[0,1,2]
df3.index=[0,1,2]
df3

   0  1    2
0  1  2  NaN
1  3  4  5.0
2  6  7  NaN

In [98]:
import copy
l1=[0,1,2]
l2 = copy.deepcopy(l1)

In [109]:
df2.iloc[0,:].between(0,10)

col1     True
col2    False
col3     True
Name: r1, dtype: bool

In [110]:
df2

    col1  col2  col3
r1    10    20    10
r2    30    40    11
r3   100   110   120